### PR TITLE
Fixed __mod to return proper modulus

### PR DESCRIPTION
**Pull request by MillaBasset**
The % operator returned the result of the division, not the remainder.

### CODE REVIEW

**Comment by romdotdog** [comment]
Thank you.

**Comment by MillaBasset** [comment]
Closing as repository owner is unlikely to fix and I'm maintaining my own fork of this.

**Comment by romdotdog** [comment]
If you're using LuaU, then my repository is more optimized for that specifically
https://github.com/romdotdog/BigInteger.lua

**Comment by MillaBasset** [comment]
I'm working with vanilla Lua 5.1 - and currently this repository / my fork is the only available option that's in pure Lua, everything else is either written in C or is for Lua 5.3 or Roblox.

I will for sure take a look at your repository should I need it in future endeavors, though.

**Comment by romdotdog** [comment]
IIRC, my repo is not hard to port to 5.1 :)
This repository I had more than just this issue with, which is why I didn't just choose your fork.

My repository uses optimized calculations and overflow hacks to achieve top speed

**Comment by MillaBasset** [comment]
I saw as much, looking in the code. From what I saw LuaU is 5.1 with 5.2/5.3 backports, and `+=` operators and the like. I don't know if it uses any 5.2/5.3 specific things, but the `+=` and co. will need to be replaced (is easy, though.)

The fork of this repository's been updated in the past day to fix most of the bugs with it, by the way. It should be suitable for use now. (I use it in my own game.)

**Pull request closed without merging**
